package lexer;
 
/**
 *  This file is automatically generated<br>
 *  - it contains the enumberation of all of the tokens
*/
public enum Tokens {
  BogusToken,Program,Void,Int,Float,
    BOOLean,If,Then,Else,While,
    Function,Return,Identifier,INTeger,FLoat,
    LeftBrace,RightBrace,LeftParen,RightParen,Comma,
    Semicolon,Assign,Equal,NotEqual,Greater,
    Less,LessEqual,Plus,Minus,Or,
    And,Multiply,Divide,Comment
}
