#!/bin/bash
#SBATCH -A cc3uv3p # 2018 XSEDE Applications of Parallel Computing Course Allocation
#SBATCH -J particle-serial
#SBATCH -o particle-serial.stdout
#SBATCH -n 1         
#SBATCH -p RM
#SBATCH -t 00:10:00     
#SBATCH -N 1         
./serial -n 1000 -o serial.txt
